name: "Consumer Contract Testing"

on:
  workflow_dispatch:
    - master;

jobs:
  consumer_test_and_publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
         java-version: '21'
         distribution: 'adopt'
         
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
         path: ~/.m2
         key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
         restore-keys: |
          ${{ runner.os }}-maven-
          
      - name: Publish Pacts to Pactflow
        run: mvn pact:publish
        env:
         PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
         PACT_BROKER_TOKEN: ${{ secrets.PACTFLOW_TOKEN_FOR_CI_CD_WORKSHOP }}
